export const MESSAGE_SUBMIT = 'MESSAGE_SUBMIT';
export const MESSAGE_RESET = 'MESSAGE_RESET';
export const MESSAGE_SUBMIT_RESULT_CONFIRM = 'MESSAGE_SUBMIT_RESULT_CONFIRM';
export const NAME_CHANGE = 'NAME_CHANGE';
export const MAIL_OR_PHONE_CHANGE = 'MAIL_OR_PHONE_CHANGE';
export const CONTENT_CHANGE = 'CONTENT_CHANGE';